### ISSUE TITLE
author(s) missing in Community Dashboard > Serlo-Community

### ISSUE THREAD

**Issue by kathongi** [serlo/stats.serlo.org#142]
The active author [MattisSeebeck](https://de.serlo.org/user/profile/MattisSeebeck) isn't displayed in the Community Dashboard "Serlo-Community".

I tried the following search filters:
* Alle Fächer & Schwellenwert =10 & Zeitraum = 90d
* Alle Fächer & Schwellenwert = 1 & Zeitraum = 1y

![image](https://user-images.githubusercontent.com/44167220/93741525-e1f4ec80-fbec-11ea-9876-67a80673cb33.png)

(Maybe other authors aren't shown in the Dashboard either?)

**Comment by kulla** [comment]
@Lodifice Do you have an idea what the issue is?

**Comment by Lodifice** [comment]
Ich bin leider gerade sehr ausgelastet, vielleicht kann ich am Wochenende mal reinschauen.

**Comment by kulla** [comment]
> Ich bin leider gerade sehr ausgelastet, vielleicht kann ich am Wochenende mal reinschauen.

Dank dir. Hat keine Eile :smile:

**Comment by Lodifice** [comment]
The problem is that is edits are not assigned so a subject in the metadata table (key_id 1). There is some metadata which sounds more specific than subject (Lagebeziehung von Punkten Geraden und Ebenen) and the key_id is 7. This however, is not counted in the subject view and therefore he has no valid edits in the table.

**Comment by kulla** [comment]
Moved to backlog document @kathongi Please push this bug in our new prio process in case it is important for you
